# -*- mode: python ; coding: utf-8 -*-
import os

a = Analysis(
    ['src/git_dungeon/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('src/git_dungeon/content/defaults', 'git_dungeon/content/defaults'),
        ('src/git_dungeon/content/packs', 'git_dungeon/content/packs'),
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'git_dungeon',
        'git_dungeon.main_cli',
        'git_dungeon.main_tui',
        'git_dungeon.engine',
        'git_dungeon.engine.model',
        'git_dungeon.engine.engine',
        'git_dungeon.engine.rules',
        'git_dungeon.engine.rules.combat_rules',
        'git_dungeon.engine.rules.progression_rules',
        'git_dungeon.engine.rules.chapter_rules',
        'git_dungeon.engine.rules.boss_rules',
        'git_dungeon.engine.rules.economy_rules',
        'git_dungeon.engine.rules.equipment_rules',
        'git_dungeon.engine.rules.skill_rules',
        'git_dungeon.engine.rng',
        'git_dungeon.engine.events',
        'git_dungeon.engine.ui',
        'git_dungeon.core',
        'git_dungeon.core.git_parser',
        'git_dungeon.core.inventory',
        'git_dungeon.core.character',
        'git_dungeon.core.combat',
        'git_dungeon.core.save_system',
        'git_dungeon.core.skills',
        'git_dungeon.core.system',
        'git_dungeon.core.resource_manager',
        'git_dungeon.core.component',
        'git_dungeon.core.entity',
        'git_dungeon.core.game_engine',
        'git_dungeon.core.lua',
        'git_dungeon.core.ultrafast_git_parser',
        'git_dungeon.config',
        'git_dungeon.config.settings',
        'git_dungeon.utils',
        'git_dungeon.utils.logger',
        'git_dungeon.utils.helpers',
        'git_dungeon.utils.exceptions',
        'git_dungeon.i18n',
        'git_dungeon.i18n.translations',
        'git_dungeon.ui',
        'git_dungeon.ui_pixel',
        'git_dungeon.ui_pixel.app',
        'git_dungeon.ui_pixel.assets',
        'git_dungeon.ui_pixel.audio',
        'git_dungeon.ui_pixel.dungeon',
        'git_dungeon.ui_pixel.resources',
        'git_dungeon.ui_pixel.screens.dungeon',
        'git_dungeon.ui_pixel.settings',
        'git_dungeon.ui_pixel.text',
        'git_dungeon.ui.combat_screen',
        'git_dungeon.ui.inventory_screen',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='GitDungeon',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
